### ISSUE TITLE
possible bug in main script

### ISSUE THREAD

**Issue by theo-krueger** [iquasere/KEGGCharter#10]
Hi, I have been trying to use the reCOGnizer output with the keggcharter and got following error message after successfully reading the data. Can you tell me whether this is a bug or a mistake on my side?

`2023-04-26 08:39:08: Arguments valid.
2023-04-26 08:39:08: Data successfully read.
Converting 27 KOs to EC numbers through the KEGG API: 100%|███████| 1/1 [00:01<00:00,  1.85s/it]
Converting 13 EC numbers to KOs through the KEGG API: 100%|███████| 1/1 [00:02<00:00,  2.16s/it]
Converting 35 EC numbers to KOs through the KEGG API: 100%|███████| 1/1 [00:02<00:00,  2.09s/it]
Traceback (most recent call last):
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'KO (KEGGCharter)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/bin/keggcharter.py", line 490, in <module>
    main()
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/bin/keggcharter.py", line 422, in main
    data, main_column = further_information(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/bin/keggcharter.py", line 121, in further_information
    data = get_cross_references(data, kegg_column=kegg_column, ko_column=ko_column, ec_column=ec_column, step=step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/bin/keggcharter.py", line 190, in get_cross_references
    data = ids_interconversion(data, column='KO (KEGGCharter)', ids_type='ko', step=step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/bin/keggcharter.py", line 157, in ids_interconversion
    ids = list(set(data[data[column].notnull()][column]))
                        ~~~~^^^^^^^^
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/lib/python3.11/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gxfs_home/geomar/smomw539/miniconda3/envs/keggcharter/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'KO (KEGGCharter)'`

**Comment by iquasere** [comment]
Hey there, thanks for reporting on this!

This does seem like a bug. Could you please provide an input file and command to reproduce this error (e.g., the ones you used).

Also, are you using the latest version - ```0.5```?

**Comment by iquasere** [comment]
Please check if this issue persists in version `0.6`. If so, don't hesitate reopening the issue.

**Comment by theo-krueger** [comment]
Hi,
I'm sorry, I must have overlooked the notification for your original reply. I just tried to rerun it and it seems to be fixed. Thank you!
